import Head from "next/head";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ECF - Le Quai Antique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logonobg.png" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap');
        </style>
      </Head>
      <Hero />
    </div>
  );
}
